import './globals.css'
import { inter } from '@/fonts'
import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'ZihtGallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`
      bg-zinc-900
      text-gray-50
      ${inter.className}
      `}>
        <Header />
        <main className='container mx-auto'>
          {children}
        </main>
      </body>
    </html>
  )
}
